export default [
  {
    name: 'Blog Title',
    desc: 'An AI tool that generates blog titles based on your blog information.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/4186/4186534.png',
    aiPrompt: 'Generate 5 engaging blog title ideas based on the given blog niche and outline. Provide the result in a bullet-point list.',
    slug: 'blog-title',
    form: [
      {
        label: 'Enter your blog niche',
        field: 'input',
        name: 'niche',
        required: true,
      },
      {
        label: 'Enter blog outline',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Blog Content',
    desc: 'An AI tool that generates detailed blog content based on your provided topic and outline.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/9623/9623631.png',
    aiPrompt: 'Create detailed blog content based on the provided topic and outline. Organize the response into structured paragraphs with clear headings.',
    slug: 'blog-content',
    form: [
      {
        label: 'Enter your blog topic',
        field: 'input',
        name: 'topic',
        required: true,
      },
      {
        label: 'Enter blog outline',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Blog Topic Ideas',
    desc: 'An AI tool that generates creative and unique blog topic ideas based on your niche.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/11497/11497847.png',
    aiPrompt: 'Generate 5 creative blog topic ideas based on the given niche. Present the topics in a clear bullet-point list.',
    slug: 'blog-topic-ideas',
    form: [
      {
        label: 'Enter your niche',
        field: 'input',
        name: 'niche',
        required: true,
      },
    ],
  },
  {
    name: 'Youtube SEO Title',
    desc: 'An AI tool that generates SEO-optimized, high-ranking YouTube video titles.',
    category: 'Youtube Tools',
    icon: 'https://cdn-icons-png.flaticon.com/128/3344/3344836.png',
    aiPrompt: 'Generate 5 SEO-friendly YouTube video titles optimized for high rankings based on the provided keywords and outline.',
    slug: 'youtube-seo-title',
    form: [
      {
        label: 'Enter your YouTube video topic keywords',
        field: 'input',
        name: 'keywords',
        required: true,
      },
      {
        label: 'Enter YouTube description outline',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Youtube Description',
    desc: 'An AI tool that generates captivating YouTube video descriptions with emojis.',
    category: 'Youtube Tools',
    icon: 'https://cdn-icons-png.flaticon.com/128/1384/1384060.png',
    aiPrompt: 'Write a captivating YouTube video description with emojis, summarizing the topic in 4-5 bullet points.',
    slug: 'youtube-description',
    form: [
      {
        label: 'Enter your video topic/title',
        field: 'input',
        name: 'topic',
        required: true,
      },
      {
        label: 'Enter YouTube outline',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Youtube Tags',
    desc: 'An AI tool that generates high-ranking YouTube tags for better video visibility.',
    category: 'Youtube Tools',
    icon: 'https://cdn-icons-png.flaticon.com/128/8359/8359651.png',
    aiPrompt: 'Generate 10 relevant and high-ranking YouTube tags based on the provided title and outline.',
    slug: 'youtube-tag',
    form: [
      {
        label: 'Enter your YouTube video title',
        field: 'input',
        name: 'title',
        required: true,
      },
      {
        label: 'Enter YouTube video outline (optional)',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Rewrite Article (Plagiarism Free)',
    desc: 'An AI tool that rewrites articles or blog posts to make them plagiarism-free.',
    category: 'Rewriting Tool',
    icon: 'https://cdn-icons-png.flaticon.com/128/4228/4228952.png',
    aiPrompt: 'Rewrite the provided article or blog post to make it plagiarism-free while preserving the original meaning.',
    slug: 'rewrite-article',
    form: [
      {
        label: 'Provide your article/blog post',
        field: 'input',
        name: 'article',
        required: true,
      },
      {
        label: 'Enter blog outline',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Text Improver',
    desc: 'An AI tool that enhances text accuracy and fluency, fixing grammar mistakes.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/4021/4021726.png',
    aiPrompt: 'Improve the provided text for accuracy and fluency, fixing grammar mistakes and optimizing clarity.',
    slug: 'text-improver',
    form: [
      {
        label: 'Enter the text you want to improve',
        field: 'input',
        name: 'textToImprove',
        required: true,
      },
      {
        label: 'Enter blog outline (optional)',
        field: 'textarea',
        name: 'outline',
      },
    ],
  },
  {
    name: 'Add Emoji to Text',
    desc: 'An AI tool that enhances text by adding relevant emojis.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/2584/2584606.png',
    aiPrompt: 'Add relevant emojis to the provided text to make it more engaging and expressive.',
    slug: 'add-emoji-to-text',
    form: [
      {
        label: 'Enter your text to add emojis',
        field: 'textarea',
        name: 'text',
        required: true,
      },
    ],
  },
  {
    name: 'Instagram Post Generator',
    desc: 'An AI tool that generates creative Instagram posts based on provided keywords.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/2111/2111463.png',
    aiPrompt: 'Generate creative Instagram post content based on the provided keywords.',
    slug: 'instagram-post',
    form: [
      {
        label: 'Enter keywords for your post',
        field: 'input',
        name: 'keywords',
        required: true,
      },
    ],
  },
  {
    name: 'Instagram Hashtag Generator',
    desc: 'An AI tool that generates trending and relevant Instagram hashtags.',
    category: 'Blog',
    icon: 'https://cdn-icons-png.flaticon.com/128/7045/7045432.png',
    aiPrompt: 'Generate a list of trending and relevant Instagram hashtags based on the provided keywords.',
    slug: 'instagram-hash-tag-generator',
    form: [
      {
        label: 'Enter keywords for your Instagram hashtag',
        field: 'input',
        name: 'keywords',
        required: true,
      },
    ],
  },
  {
    name: 'English Grammar Check',
    desc: 'AI Model to correct your English grammar by analyzing the text.',
    category: 'English Grammar Check',
    icon: 'https://cdn-icons-png.flaticon.com/128/15270/15270892.png',
    aiPrompt: 'Analyze the provided text for grammar, punctuation, and sentence structure errors. Suggest improvements and provide a corrected version of the text.',
    slug: 'english-grammar-check',
    form: [
      {
        label: 'Enter your text for grammar checking',
        field: 'textarea',
        name: 'text',
        required: true,
      },
    ],
  },
  {
    name: 'Write Code',
    desc: 'AI Model to generate programming code in any language.',
    category: 'Programming',
    icon: 'https://cdn-icons-png.flaticon.com/128/7069/7069896.png',
    aiPrompt: 'Generate a complete programming code snippet based on the provided programming language, functionality description, and requirements. Include comments for clarity.',
    slug: 'write-code',
    form: [
      {
        label: 'Describe the functionality or code requirements',
        field: 'textarea',
        name: 'requirements',
        required: true,
      },
      {
        label: 'Enter the programming language',
        field: 'input',
        name: 'language',
        required: true,
      },
    ],
  },
  {
    name: 'Explain Code',
    desc: 'AI Model to explain programming code in any language.',
    category: 'Programming',
    icon: 'https://cdn-icons-png.flaticon.com/128/13541/13541104.png',
    aiPrompt: 'Analyze and explain the provided programming code in clear and simple terms. Describe the functionality of each part, including variables, functions, and logic.',
    slug: 'explain-code',
    form: [
      {
        label: 'Enter the programming code you want explained',
        field: 'textarea',
        name: 'code',
        required: true,
      },
      {
        label: 'Mention the programming language (optional)',
        field: 'input',
        name: 'language',
      },
    ],
  },
  {
    name: 'Resume Builder',
    desc: 'An AI tool that creates professional resumes tailored to your preferences and job requirements.',
    category: 'Career Tools',
    icon: 'https://cdn-icons-png.flaticon.com/128/2921/2921222.png',
    aiPrompt: 'Generate a professional and visually appealing resume based on the provided information, including work experience, education, skills, and career objectives. Ensure it is formatted for readability and impact.',
    slug: 'resume-builder',
    form: [
      {
        label: 'Enter your full name',
        field: 'input',
        name: 'fullName',
        required: true,
      },
      {
        label: 'Enter your contact information',
        field: 'textarea',
        name: 'contactInfo',
        required: true,
      },
      {
        label: 'Enter your work experience',
        field: 'textarea',
        name: 'workExperience',
        required: true,
      },
      {
        label: 'Enter your education',
        field: 'textarea',
        name: 'education',
        required: true,
      },
      {
        label: 'Enter your skills',
        field: 'textarea',
        name: 'skills',
        required: true,
      },
      {
        label: 'Enter your career objective (optional)',
        field: 'textarea',
        name: 'careerObjective',
      },
      {
        label: 'Choose a resume format',
        field: 'select',
        name: 'format',
        options: ['Modern', 'Classic', 'Minimalist', 'Creative'],
        required: true,
      },
    ],
  },  
];
